var jcontent = [
  {
    "S.NO": 1,
    District: "Ariyalur",
    Institution: "A.S Hospital",
    covid: 1,
    oxygen: 0,
    icu: 1,
  },
  {
    "S.NO": 2,
    District: "Ariyalur",
    Institution: "Golden Hospital",
    covid: 1,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 3,
    District: "Chengalpattu",
    Institution: "Annai Arul Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 4,
    District: "Chengalpattu",
    Institution: "Chennai Emergency care Centre Pammal",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 5,
    District: "Chengalpattu",
    Institution: "Dr. Rela Institute",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 6,
    District: "Chengalpattu",
    Institution: "Sudar Hospitals, Hasthinapuram",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 7,
    District: "Chengalpattu",
    Institution: "Sugam Hospital, Chromepet",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 8,
    District: "Chengalpattu",
    Institution: "Deepam Hospitals, West Tambaram",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 9,
    District: "Chennai",
    Institution: "Apollo Hospital, Greams Road",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 10,
    District: "Chennai",
    Institution: "Apollo Hospitals, Vanagaram",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 11,
    District: "Chennai",
    Institution: "Appasamy Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 12,
    District: "Chennai",
    Institution: "ArunVijaya Hospitals, KK Nagar",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 13,
    District: "Chennai",
    Institution: "Astra Ortho N Spine Care Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 14,
    District: "Chennai",
    Institution: "Aysha Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 15,
    District: "Chennai",
    Institution: "Be Well Hospital Anna nagar",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 16,
    District: "Chennai",
    Institution: "Bhaarath medical college and hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 17,
    District: "Chennai",
    Institution: "Bharathiraja Hospital & Research Centre Pvt Ltd",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 18,
    District: "Chennai",
    Institution: "Billroth Hospitals Shenoy Nagar, Chennai TN.",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 19,
    District: "Chennai",
    Institution: "Bloom Fertility and Healthcare, Velachery",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 20,
    District: "Chennai",
    Institution: "C.s.i Rainy Multi Speciality Hospital Tondaiarpet",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 21,
    District: "Chennai",
    Institution: "Chennai Orthopedic Centre -ER",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 22,
    District: "Chennai",
    Institution: "Chettinad Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 23,
    District: "Chennai",
    Institution: "CSI Kalyani General Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 24,
    District: "Chennai",
    Institution: "Dr.Kamakshi Memorial Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 25,
    District: "Chennai",
    Institution: "Fortis Malar Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 26,
    District: "Chennai",
    Institution: "Frontier Lifeline Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 27,
    District: "Chennai",
    Institution: "Girishwari Hospital Alwarpet",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 28,
    District: "Chennai",
    Institution: "GKM Hospital Pvt Ltd",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 29,
    District: "Chennai",
    Institution: "GLB Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 30,
    District: "Chennai",
    Institution: "Gleneagles Global Health City",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 31,
    District: "Chennai",
    Institution: "Gunasekaran Hospitals Pvt Ltd",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 32,
    District: "Chennai",
    Institution: "Hycare Super Speciality Hospital",
    covid: 10,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 33,
    District: "Chennai",
    Institution: "K.P Hospital, Adambakkam",
    covid: 6,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 34,
    District: "Chennai",
    Institution: "Kanchi Kamakoti Child Trust Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 35,
    District: "Chennai",
    Institution: "Karpaga Vinayaga Medical Science & Ri",
    covid: 144,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 36,
    District: "Chennai",
    Institution: "Kauvery Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 37,
    District: "Chennai",
    Institution: "Kumaran Hospital Pvt ltd",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 38,
    District: "Chennai",
    Institution: "KVT Speciality Hospital, Erukanchery",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 39,
    District: "Chennai",
    Institution: "Laksha Hospital Royapettah",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 40,
    District: "Chennai",
    Institution: "Life Care Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 41,
    District: "Chennai",
    Institution: "Lifeline Hospitals",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 42,
    District: "Chennai",
    Institution: "M G M Health Care Pvt Ltd",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 43,
    District: "Chennai",
    Institution: "M.R Hospital",
    covid: 1,
    oxygen: 1,
    icu: 0,
  },
  {
    "S.NO": 44,
    District: "Chennai",
    Institution: "Maya Nursing Home",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 45,
    District: "Chennai",
    Institution: "Medway Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 46,
    District: "Kancheepuram",
    Institution: "Meenakshi Medical College",
    covid: 20,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 47,
    District: "Chennai",
    Institution: "Melmaruvathur Aadhiparasakthi Medical College",
    covid: 11,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 48,
    District: "Chennai",
    Institution: "Mint Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 49,
    District: "Chennai",
    Institution: "Miot Hospital",
    covid: 23,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 50,
    District: "Chennai",
    Institution: "MMRV Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 51,
    District: "Chennai",
    Institution: "Muthu hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 52,
    District: "Chennai",
    Institution: "National Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 53,
    District: "Chennai",
    Institution: "New Hope Multi Speciality Hospital, Kilpauk",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 54,
    District: "Chennai",
    Institution: "Medway Hospital,Mugappair",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 55,
    District: "Chennai",
    Institution: "New Lifemed Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 56,
    District: "Chennai",
    Institution: "Noble Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 57,
    District: "Chennai",
    Institution: "Orthomed Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 58,
    District: "Chennai",
    Institution: "Padmini Nursing Home Chetpet",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 59,
    District: "Chennai",
    Institution: "Panimalar Medical College & Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 60,
    District: "Chennai",
    Institution: "Prashanth Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 61,
    District: "Chennai",
    Institution: "Rama Rau Polyclinc, Kilpauk",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 62,
    District: "Chennai",
    Institution: "Retteri Sri Kumaran Health Centre (P) Ltd, Kolathur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 63,
    District: "Chennai",
    Institution: "RPS hospital pvt ltd",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 64,
    District: "Chennai",
    Institution: "Sai Speed Hospital, Arumbakkam",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 65,
    District: "Chennai",
    Institution: "Sakthi Hospital Research Centre Triplicane",
    covid: 5,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 66,
    District: "Chennai",
    Institution: "Saveetha Medical College",
    covid: 13,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 67,
    District: "Chennai",
    Institution: "SIMS Hospital Vadapalani",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 68,
    District: "Chennai",
    Institution: "Sivam Hospitals, Ullagaram",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 69,
    District: "Chennai",
    Institution: "Sooriya Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 70,
    District: "Chennai",
    Institution: "Sree Balaji Medical College & Hospital",
    covid: 17,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 71,
    District: "Chennai",
    Institution: "Sree Lakshmi Clinic and Maternity Centre",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 72,
    District: "Chennai",
    Institution: "Sri Ramachandra Medical College Hospital, Porur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 73,
    District: "Chennai",
    Institution: "Sri Sathya Sai Medical College & Research Institue",
    covid: 316,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 74,
    District: "Chennai",
    Institution: "Srinivas Priya Hospital Perambur",
    covid: 2,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 75,
    District: "Chennai",
    Institution: "Srinivasan Rajalakshmi Memorial Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 76,
    District: "Chennai",
    Institution: "Srm Medical College & Hospital",
    covid: 167,
    oxygen: 11,
    icu: 0,
  },
  {
    "S.NO": 77,
    District: "Chennai",
    Institution: "St. Thomas Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 78,
    District: "Chennai",
    Institution: "Sundaram Medical Foundation",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 79,
    District: "Chennai",
    Institution: "Tagore Medical College & Hospital",
    covid: 154,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 80,
    District: "Chennai",
    Institution: "The Guest Hospital, Kilpauk",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 81,
    District: "Chennai",
    Institution: "Tosh Hospitals Pvt Ltd",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 82,
    District: "Chennai",
    Institution: "Trinity Acute care Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 83,
    District: "Chennai",
    Institution: "Vasantha Subramanian Hospitals Pvt Ltd, Chetpet",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 84,
    District: "Chennai",
    Institution: "Venkateswara Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 85,
    District: "Chennai",
    Institution: "Vhs, Adayar",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 86,
    District: "Chennai",
    Institution: "Vihaa Hospital Anna Nagar",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 87,
    District: "Chennai",
    Institution: "Vijaya Group Of Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 88,
    District: "Chennai",
    Institution:
      "Sims (Srm Institutes For Medical Science Hospital) Nungumbakkam",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 89,
    District: "Chennai",
    Institution: "KMS Health Centre Pvt Ltd,Selaiyur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 90,
    District: "Chennai",
    Institution: "Nichani Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 91,
    District: "Chennai",
    Institution: "Dr.Metha hospital Chetpet",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 92,
    District: "Coimbatore",
    Institution: "G. Kuppusamy Naidu Hospital",
    covid: 108,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 93,
    District: "Coimbatore",
    Institution: "Hindusthan Hospital, Udaiyampalayam",
    covid: 15,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 94,
    District: "Coimbatore",
    Institution: "Karpagam Faculty Medical College And Hospital",
    covid: 4,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 95,
    District: "Coimbatore",
    Institution: "KG Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 96,
    District: "Coimbatore",
    Institution: "Kongunad Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 97,
    District: "Coimbatore",
    Institution: "Kovai Medical College Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 98,
    District: "Coimbatore",
    Institution: "One Care Medical Centre",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 99,
    District: "Coimbatore",
    Institution: "PSG Institute Of Medical Sciences and Research, Coimbatore",
    covid: 10,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 100,
    District: "Coimbatore",
    Institution: "Royal Care Super Speciality Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 101,
    District: "Coimbatore",
    Institution: "Royal Care Super Speciality Hospital Gandhipuram",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 102,
    District: "Coimbatore",
    Institution: "Sri Ramakrishna Hospital",
    covid: 3,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 103,
    District: "Coimbatore",
    Institution: "KMCH Kovilampalayam Hospital, Sathy Road",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 104,
    District: "Cuddalore",
    Institution: "NLCIL Hospital,Neyveli",
    covid: 15,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 105,
    District: "Dindigul",
    Institution: "Christian Fellow Community Centre",
    covid: 50,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 106,
    District: "Dindigul",
    Institution: "Christian Fellowship Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 107,
    District: "Dindigul",
    Institution: "Leonard Hospital",
    covid: 67,
    oxygen: 2,
    icu: 0,
  },
  {
    "S.NO": 108,
    District: "Dindigul",
    Institution: "St.Joseph Hospital",
    covid: 40,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 109,
    District: "Dindigul",
    Institution: "Vel Multispeciality Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 110,
    District: "Erode",
    Institution: "Erode Medical Centre",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 111,
    District: "Erode",
    Institution: "Maaruthi Medical Centre And Hospital",
    covid: 10,
    oxygen: 4,
    icu: 3,
  },
  {
    "S.NO": 112,
    District: "Erode",
    Institution: "Sudha Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 113,
    District: "Kallakurichi",
    Institution: "Annai Medical Centre",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 114,
    District: "Kallakurichi",
    Institution: "E.S. Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 115,
    District: "Kallakurichi",
    Institution: "I Med Super Speciality Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 116,
    District: "Kallakurichi",
    Institution: "Lotus Paediatric Emergency Centre",
    covid: 11,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 117,
    District: "Kallakurichi",
    Institution: "Maragadam Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 118,
    District: "Kallakurichi",
    Institution: "S A Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 119,
    District: "Kallakurichi",
    Institution: "Sri Sanjeevi Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 120,
    District: "Kancheepuram",
    Institution: "Bon Secuors Hospital",
    covid: 15,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 121,
    District: "Kancheepuram",
    Institution: "Chennai Urology & Robotics Institute Hospital Thoraippakkam",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 122,
    District: "Kancheepuram",
    Institution: "Madha Medical College&Research Institute",
    covid: 438,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 123,
    District: "Kancheepuram",
    Institution: "Sri Muthukumaran Medical College",
    covid: 308,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 124,
    District: "Kancheepuram",
    Institution: "Apollo Medical Centre Karapakkam",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 125,
    District: "Kanyakumari",
    Institution: "Bensam Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 126,
    District: "Kanyakumari",
    Institution: "C.S.I.MISSION HOSPITAL",
    covid: 76,
    oxygen: 40,
    icu: 2,
  },
  {
    "S.NO": 127,
    District: "Kanyakumari",
    Institution: "Dr. Jayasekaran Medical Trust Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 128,
    District: "Kanyakumari",
    Institution: "Sree Mookambika Institute of Medical Sciences",
    covid: 131,
    oxygen: 75,
    icu: 10,
  },
  {
    "S.NO": 129,
    District: "Kanyakumari",
    Institution: "Vasantham Health Centre",
    covid: 1,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 130,
    District: "Karur",
    Institution: "Amaravathi Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 131,
    District: "Karur",
    Institution: "Apollo Logo Hospital,Karur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 132,
    District: "Krishnagiri",
    Institution: "Chandrasekara Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 133,
    District: "Krishnagiri",
    Institution: "Kauvery Hospital, Hosur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 134,
    District: "Madurai",
    Institution: "Apollo Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 135,
    District: "Madurai",
    Institution: "Bharathi Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 136,
    District: "Madurai",
    Institution: "Devadoss Multispeciality Hospital",
    covid: 5,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 137,
    District: "Madurai",
    Institution: "Guru Multispeciality Hospital",
    covid: 11,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 138,
    District: "Madurai",
    Institution: "Harshini Hospital,Sathamangalam",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 139,
    District: "Madurai",
    Institution: "Harshitha Hospital, Avaniyapuram",
    covid: 5,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 140,
    District: "Madurai",
    Institution: "Lakshmana Multispeciality Hospital",
    covid: 4,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 141,
    District: "Madurai",
    Institution: "Meenakshi Mission Hospital and Research Centre",
    covid: 21,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 142,
    District: "Madurai",
    Institution: "Rahavendhar Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 143,
    District: "Madurai",
    Institution: "Saravana Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 144,
    District: "Madurai",
    Institution: "Shenbagam Hospitals Pvt Ltd.",
    covid: 7,
    oxygen: 6,
    icu: 1,
  },
  {
    "S.NO": 145,
    District: "Madurai",
    Institution: "Sumathi Hospital & Fertility Center,Anna Nagar",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 146,
    District: "Madurai",
    Institution: "Thembavani Hospital,Gnanaolipuram",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 147,
    District: "Madurai",
    Institution: "Vadamalayan Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 148,
    District: "Madurai",
    Institution: "Velammal Medical College Hospital and Research Institute",
    covid: 52,
    oxygen: 12,
    icu: 0,
  },
  {
    "S.NO": 149,
    District: "Mayiladuthurai",
    Institution: "Cahoj Hospital",
    covid: 17,
    oxygen: 6,
    icu: 0,
  },
  {
    "S.NO": 150,
    District: "Mayiladuthurai",
    Institution: "Ram Bone And Joint Hospial",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 151,
    District: "Mayiladuthurai",
    Institution: "Shanthi Nursing Home",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 152,
    District: "Namakkal",
    Institution: "Aravinth Hospital",
    covid: 5,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 153,
    District: "Namakkal",
    Institution: "M.M.Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 154,
    District: "Namakkal",
    Institution: "Maharaja Speciality Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 155,
    District: "Namakkal",
    Institution: "Thangam Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 156,
    District: "Namakkal",
    Institution: "Vivekanandha Medical Care Hospital",
    covid: 5,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 157,
    District: "TheNilgiris",
    Institution: "Ashwini Gudalur Tribal Hospital",
    covid: 4,
    oxygen: 4,
    icu: 0,
  },
  {
    "S.NO": 158,
    District: "TheNilgiris",
    Institution: "Nankam Hospital",
    covid: 9,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 159,
    District: "TheNilgiris",
    Institution: "Sagayamatha Hospital",
    covid: 9,
    oxygen: 1,
    icu: 0,
  },
  {
    "S.NO": 160,
    District: "Perambalur",
    Institution: "Amma Hospital Thuraimangalam",
    covid: 5,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 161,
    District: "Perambalur",
    Institution: "Aruptha Multispeciality Hospital",
    covid: 7,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 162,
    District: "Perambalur",
    Institution: "Devi Hospital Elambalur",
    covid: 8,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 163,
    District: "Perambalur",
    Institution: "Dhanalakshmisrinivasan Medical College And Hospital",
    covid: 174,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 164,
    District: "Perambalur",
    Institution: "Dr. Venkatesan Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 165,
    District: "Perambalur",
    Institution: "Lakshmi Nursing Home",
    covid: 10,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 166,
    District: "Perambalur",
    Institution: "Madhu Hospital",
    covid: 1,
    oxygen: 1,
    icu: 0,
  },
  {
    "S.NO": 167,
    District: "Perambalur",
    Institution: "Niranjan Nursing Home",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 168,
    District: "Perambalur",
    Institution: "Pedro Nursing Home",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 169,
    District: "Perambalur",
    Institution: "Ramasamy Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 170,
    District: "Perambalur",
    Institution: "Siva Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 171,
    District: "Perambalur",
    Institution: "SPT Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 172,
    District: "Pudukkottai",
    Institution: "Muthu Meenakshi Hospitals",
    covid: 33,
    oxygen: 7,
    icu: 15,
  },
  {
    "S.NO": 173,
    District: "Ramanathapuram",
    Institution: "Aasi Multi Speciality Hospital",
    covid: 27,
    oxygen: 20,
    icu: 7,
  },
  {
    "S.NO": 174,
    District: "Ramanathapuram",
    Institution: "Kanagamani Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 175,
    District: "Ramanathapuram",
    Institution: "Vel Hospital Ramanathapuram",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 176,
    District: "Salem",
    Institution: "Annapoorna Medical College and Hospital",
    covid: 13,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 177,
    District: "Salem",
    Institution: "Dharan Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 178,
    District: "Salem",
    Institution: "Kauvery Hospital, Salem",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 179,
    District: "Salem",
    Institution: "Kurinji Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 180,
    District: "Salem",
    Institution: "Manipal Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 181,
    District: "Salem",
    Institution: "Priyam Speciality Hospitals",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 182,
    District: "Salem",
    Institution: "Shanmuga Hospital Cancer Institute",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 183,
    District: "Salem",
    Institution: "SKS Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 184,
    District: "Salem",
    Institution: "Sri Gokulam Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 185,
    District: "Salem",
    Institution: "Vinayaka Mission Super Specialty Hospitals Pvt Ltd",
    covid: 15,
    oxygen: 2,
    icu: 8,
  },
  {
    "S.NO": 186,
    District: "Salem",
    Institution:
      "Vinyaga Mission Kirubanandha Variyar Medical College Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 187,
    District: "Sivagangai",
    Institution: "Kauvery Hospital Karaikudi",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 188,
    District: "Thanjavur",
    Institution: "KG Multi Speciality Hospital",
    covid: 13,
    oxygen: 11,
    icu: 2,
  },
  {
    "S.NO": 189,
    District: "Thanjavur",
    Institution: "Meenakshi Multispeciality Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 190,
    District: "Tiruvallur",
    Institution: "Aakash Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 191,
    District: "Tiruvallur",
    Institution: "ACS Medical College And Hospital",
    covid: 34,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 192,
    District: "Tiruvallur",
    Institution: "Peacock Hospitals Private Limited",
    covid: 1,
    oxygen: 0,
    icu: 1,
  },
  {
    "S.NO": 193,
    District: "Tiruvallur",
    Institution: "Raj Nursing Home Mogappair East",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 194,
    District: "Tiruvallur",
    Institution: "Ravina Health Care Pvt Ltd",
    covid: 6,
    oxygen: 3,
    icu: 0,
  },
  {
    "S.NO": 195,
    District: "Tiruvallur",
    Institution: "Sri Ivan Stedeford Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 196,
    District: "Tiruvallur",
    Institution: "Sugam Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 197,
    District: "Tiruvannamalai",
    Institution: "Ramana Maharishi Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 198,
    District: "Thoothukudi",
    Institution: "Sacred Heart Hospital",
    covid: 13,
    oxygen: 8,
    icu: 0,
  },
  {
    "S.NO": 199,
    District: "Thoothukudi",
    Institution: "Sri Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 200,
    District: "Tirunelveli",
    Institution: "Annai Velankanni Multi Speciality Hospital, Palayamkottai",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 201,
    District: "Tirunelveli",
    Institution: "Ponra Multispeciality Hospital",
    covid: 1,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 202,
    District: "Tirunelveli",
    Institution: "Rosemary mission hospital and research centre",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 203,
    District: "Dindigul",
    Institution: "Shifa Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 204,
    District: "Tiruppur",
    Institution: "Revathi Medical Centre",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 205,
    District: "Thiruvarur",
    Institution: "Navajeevan Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 206,
    District: "Thiruvarur",
    Institution: "Thiruvarur Medical Centre",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 207,
    District: "Thiruchirappalli",
    Institution: "Neuro One Hospital, Karur Bye Pass Road",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 208,
    District: "Thiruchirappalli",
    Institution: "Apollo Speciality Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 209,
    District: "Thiruchirappalli",
    Institution: "G V N Hospital Pvt Ltd",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 210,
    District: "Thiruchirappalli",
    Institution: "Kavery Medical Centre And Hospital, Trichy",
    covid: 13,
    oxygen: 3,
    icu: 0,
  },
  {
    "S.NO": 211,
    District: "Thiruchirappalli",
    Institution: "Maruti Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 212,
    District: "Thiruchirappalli",
    Institution: "Sinduja Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 213,
    District: "Thiruchirappalli",
    Institution: "SRM Medical College Hospital And Research Centre, Trichy",
    covid: 36,
    oxygen: 2,
    icu: 3,
  },
  {
    "S.NO": 214,
    District: "Thiruchirappalli",
    Institution: "Dr.G.Viswanathan Hospital Mambalasalai",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 215,
    District: "Thiruchirappalli",
    Institution: "Pankajam Sitaram Nursing Home (A Unit Of GVN Hospital)",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 216,
    District: "Thiruchirappalli",
    Institution: "Sundaram Hospital, Pudhur",
    covid: 1,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 217,
    District: "Thoothukudi",
    Institution: "Kamala Speciality Hospitals Pvt Ltd, Kovilpatti",
    covid: 7,
    oxygen: 3,
    icu: 1,
  },
  {
    "S.NO": 218,
    District: "Vellore",
    Institution: "Apollo KH Hospital Ranipet",
    covid: 2,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 219,
    District: "Vellore",
    Institution: "Christian Medical College",
    covid: 29,
    oxygen: 29,
    icu: 0,
  },
  {
    "S.NO": 220,
    District: "Vellore",
    Institution: "Christian Medical College Kannigipuram campus",
    covid: 51,
    oxygen: 51,
    icu: 0,
  },
  {
    "S.NO": 221,
    District: "Vellore",
    Institution: "Sri Narayani Hospital and Research Centre",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 222,
    District: "Virudhunagar",
    Institution: "Meenakshi Memorial Hospital",
    covid: 1,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 223,
    District: "Virudhunagar",
    Institution: "Sri Krishna Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 224,
    District: "Chengalpattu",
    Institution: "Sai Fertility Centre & Hospital, Vedhachalam Nagar",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 225,
    District: "Dindigul",
    Institution: "City Hospital Gandhi Nagar",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 226,
    District: "Dindigul",
    Institution: "Raja Rajeswari Hospital, Spence Nagar",
    covid: 9,
    oxygen: 6,
    icu: 3,
  },
  {
    "S.NO": 227,
    District: "Madurai",
    Institution: "Santhya Speciality Hospital, Arappalaiyam Main Road",
    covid: 12,
    oxygen: 3,
    icu: 4,
  },
  {
    "S.NO": 228,
    District: "Ramanathapuram",
    Institution: "Arogya Hospital, Kenikarai",
    covid: 30,
    oxygen: 20,
    icu: 10,
  },
  {
    "S.NO": 229,
    District: "Salem",
    Institution: "Saravana Hospital Ponnamapet",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 230,
    District: "Thiruchirappalli",
    Institution: "Sri Venkateswara Hospital T.V Koil",
    covid: 4,
    oxygen: 4,
    icu: 0,
  },
  {
    "S.NO": 231,
    District: "Madurai",
    Institution: "Aristo Speciality Hospital Ponmeni",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 232,
    District: "Madurai",
    Institution: "Asirvatham Speciality Hospital, Gandhi Nagar",
    covid: 25,
    oxygen: 4,
    icu: 2,
  },
  {
    "S.NO": 233,
    District: "Madurai",
    Institution: "Bala Hospital Usilampatti",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 234,
    District: "Madurai",
    Institution: "KJS Speciality Hospital,K.Pudur",
    covid: 10,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 235,
    District: "Madurai",
    Institution: "Nithilaa Nursing Home Palanganatham",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 236,
    District: "Madurai",
    Institution: "NTC Hospitals Vaithiyanathapuram",
    covid: 8,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 237,
    District: "Madurai",
    Institution: "Raks Hospital Anna Nagar",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 238,
    District: "Chennai",
    Institution: "Pon Malligai Hospital Adambakkam",
    covid: 19,
    oxygen: 8,
    icu: 0,
  },
  {
    "S.NO": 239,
    District: "Chennai",
    Institution: "Iswarya Fertility Centre Kilpauk",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 240,
    District: "Chennai",
    Institution: "Iswarya Fertility Centre Adyar",
    covid: 10,
    oxygen: 3,
    icu: 2,
  },
  {
    "S.NO": 241,
    District: "Chennai",
    Institution: "Iswarya Fertility Centre Ambattur",
    covid: 5,
    oxygen: 2,
    icu: 1,
  },
  {
    "S.NO": 242,
    District: "Chengalpattu",
    Institution: "Parvathy Hospital Chrompet,",
    covid: 20,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 243,
    District: "Chennai",
    Institution: "Shaarave Multi Speciality Hospital, Sowcorpet",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 244,
    District: "Chennai",
    Institution: "Shanmugam Multi Speciality Hospital Royapuram",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 245,
    District: "Coimbatore",
    Institution: "Atlas Pain Care Sowripalayam",
    covid: 9,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 246,
    District: "Dindigul",
    Institution: "JCB Hospitals Palani Road,",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 247,
    District: "Dindigul",
    Institution: "Shree SathyaSubha Hospital, New Agaraharam",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 248,
    District: "Dindigul",
    Institution: "Van Allen Hospital, Kodaikanal",
    covid: 4,
    oxygen: 3,
    icu: 1,
  },
  {
    "S.NO": 249,
    District: "Kanyakumari",
    Institution: "Swamiyarmadam Rathna Memorial Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 250,
    District: "Krishnagiri",
    Institution: "Vijay Sai Health Care Pvt Ltd",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 251,
    District: "Madurai",
    Institution: "Rio Hospital Vandiyur",
    covid: 14,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 252,
    District: "Salem",
    Institution: "Universal Cancer Hospital, Kondalampatty",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 253,
    District: "Sivagangai",
    Institution: "Devaki Multi Speciality Hospital",
    covid: 2,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 254,
    District: "Sivagangai",
    Institution: "Karthick Multi Speciality Hospital",
    covid: 5,
    oxygen: 4,
    icu: 1,
  },
  {
    "S.NO": 255,
    District: "Thiruchirappalli",
    Institution: "Velan Speciality Hospital, Highways Colony",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 256,
    District: "Thoothukudi",
    Institution: "Public Welfare Hospital Kovilpatti",
    covid: 4,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 257,
    District: "Chennai",
    Institution: "Medway Women Centre, Kodambakkam",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 258,
    District: "Dindigul",
    Institution: "K T Hospitals, Palani Bye pass Junction",
    covid: 35,
    oxygen: 25,
    icu: 10,
  },
  {
    "S.NO": 259,
    District: "Madurai",
    Institution: "Raksha Hospital, Anna Nagar",
    covid: 9,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 260,
    District: "Madurai",
    Institution: "Thirusenthilandavar Multispeciality Hospital",
    covid: 20,
    oxygen: 2,
    icu: 2,
  },
  {
    "S.NO": 261,
    District: "Sivagangai",
    Institution: "Madha Hospital, Manamadurai",
    covid: 23,
    oxygen: 2,
    icu: 10,
  },
  {
    "S.NO": 262,
    District: "Madurai",
    Institution: "Ahana Hospital,11,Subramanian st,Annanagar,Madurai",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 263,
    District: "Chennai",
    Institution: "Apollo Hospital, OMR, Perungudi",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 264,
    District: "Chennai",
    Institution: "K.G.J Hospitals, Korattur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 265,
    District: "Chennai",
    Institution: "Padmapriya Hospital, Adyar",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 266,
    District: "Chennai",
    Institution: "Priya Nursing Home, Old Washermenpet",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 267,
    District: "Chennai",
    Institution: "Saraswathy Multi Speciality Hospitals, Madipakkam",
    covid: 1,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 268,
    District: "Chennai",
    Institution: "Suman Hospital, Thiruvotriyur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 269,
    District: "Chennai",
    Institution: "The Madras Medical Mission, Mogappair",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 270,
    District: "Coimbatore",
    Institution: "Abinand Hospital",
    covid: 13,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 271,
    District: "Coimbatore",
    Institution: "Sree Abirami Hospital, Coimbatore TN.",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 272,
    District: "Erode",
    Institution: "Kovai Medical Centre,Erode TN.",
    covid: 50,
    oxygen: 20,
    icu: 0,
  },
  {
    "S.NO": 273,
    District: "Kancheepuram",
    Institution: "TCS, Sirucherry",
    covid: 13,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 274,
    District: "Kanyakumari",
    Institution: "Bethesda Hospital, Nagercoil",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 275,
    District: "Kanyakumari",
    Institution: "Siva Hospital, Nagercoil",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 276,
    District: "Karur",
    Institution: "ABS Hospital, Thanthonimalai",
    covid: 5,
    oxygen: 2,
    icu: 3,
  },
  {
    "S.NO": 277,
    District: "Krishnagiri",
    Institution: "Sri Chandrasekaran Hospital unit -2, Hosur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 278,
    District: "Madurai",
    Institution: "BGM Hospital, Iyer Bungalow",
    covid: 8,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 279,
    District: "Madurai",
    Institution: "Dr.Chidambaram Memorial Hospital, Jai Hind puram",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 280,
    District: "Madurai",
    Institution: "Gowri Nursing Home, Jeeva Nagar",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 281,
    District: "Madurai",
    Institution: "Grace Kennett Foundation Hospital, Kennett Road",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 282,
    District: "Madurai",
    Institution:
      "Swarnakamalam (SKG) Multispeciality Hospital Pvt Ltd, Thirumanagalam",
    covid: 21,
    oxygen: 3,
    icu: 13,
  },
  {
    "S.NO": 283,
    District: "Nagapattinam",
    Institution: "Arun Priya Nursing Home, Nagapattinam TN.",
    covid: 15,
    oxygen: 9,
    icu: 0,
  },
  {
    "S.NO": 284,
    District: "Ramanathapuram",
    Institution: "Meera Clinic",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 285,
    District: "Salem",
    Institution: "Geeth Raghunath Hospital, Attur",
    covid: 2,
    oxygen: 0,
    icu: 2,
  },
  {
    "S.NO": 286,
    District: "Salem",
    Institution: "Karthik Medical Centre, Idappadi",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 287,
    District: "Salem",
    Institution: "Shivasurya Polyclinic, Salem",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 288,
    District: "Salem",
    Institution: "Sree Vasantham Hospital, Gugai",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 289,
    District: "Tenkasi",
    Institution: "Meeran Hospital, Tenkasi",
    covid: 10,
    oxygen: 10,
    icu: 0,
  },
  {
    "S.NO": 290,
    District: "Tenkasi",
    Institution: "Santhi Hospital, Vaikkalpalam, Tenkasi",
    covid: 7,
    oxygen: 2,
    icu: 5,
  },
  {
    "S.NO": 291,
    District: "Thanjavur",
    Institution: "Our Lady Hospital",
    covid: 26,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 292,
    District: "Thanjavur",
    Institution: "Sri Naadi Hospital, Pattukottai",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 293,
    District: "Thanjavur",
    Institution: "Vijay Poly Clinic, Kumbakonam",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 294,
    District: "Theni",
    Institution: "Arun Hospital",
    covid: 23,
    oxygen: 10,
    icu: 3,
  },
  {
    "S.NO": 295,
    District: "Theni",
    Institution: "Nalam Hospital, Allinagaram",
    covid: 1,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 296,
    District: "Theni",
    Institution: "Ramapadyan Hospital, A.Pudur Vilakku",
    covid: 7,
    oxygen: 2,
    icu: 2,
  },
  {
    "S.NO": 297,
    District: "Theni",
    Institution: "Theni Medical Centre, Nehruji Road",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 298,
    District: "Tirunelveli",
    Institution: "Royal Hospital, NGO Colony",
    covid: 5,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 299,
    District: "Tirunelveli",
    Institution: "Sudharson Platinum Hospitals, Vannarpettai",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 300,
    District: "Thiruchirappalli",
    Institution: "Athma Hospitals, Thillai Nagar",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 301,
    District: "Thiruchirappalli",
    Institution: "Kavi Hospital & Neuro Foundation",
    covid: 3,
    oxygen: 1,
    icu: 2,
  },
  {
    "S.NO": 302,
    District: "Thiruchirappalli",
    Institution: "Mangalam Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 303,
    District: "Thiruchirappalli",
    Institution: "MMM Multi Speciality Hospital",
    covid: 20,
    oxygen: 10,
    icu: 5,
  },
  {
    "S.NO": 304,
    District: "Thiruchirappalli",
    Institution: "Retna Global Hospital, Tennur",
    covid: 1,
    oxygen: 1,
    icu: 0,
  },
  {
    "S.NO": 305,
    District: "Thiruchirappalli",
    Institution: "Star KIMS Hospital, Thillai Nagar",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 306,
    District: "Thiruchirappalli",
    Institution: "Trichy Medical Centre and Hospital, Thillai Nagar",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 307,
    District: "Thoothukudi",
    Institution: "Aarthi Hospital, Kovilpatti",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 308,
    District: "Thoothukudi",
    Institution: "City Hospital, Tuticorin",
    covid: 7,
    oxygen: 5,
    icu: 2,
  },
  {
    "S.NO": 309,
    District: "Thoothukudi",
    Institution: "K.M.T Hospital, Kayalpatnam",
    covid: 6,
    oxygen: 1,
    icu: 5,
  },
  {
    "S.NO": 310,
    District: "Thoothukudi",
    Institution: "Sree Chendur Multispeciality Hospital, Kovilpatti",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 311,
    District: "Thoothukudi",
    Institution: "Suganthi Nursing Home (Unit of Sundaram Arulrhaj Hospitals)",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 312,
    District: "Virudhunagar",
    Institution: "VVVNC, Chatrarediapatti",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 313,
    District: "Chennai",
    Institution: "Dr. Mehtas Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 314,
    District: "Tirunelveli",
    Institution: "Shifa Hospital",
    covid: 1,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 315,
    District: "Chennai",
    Institution: "Annai Multispeciality Hospital",
    covid: 2,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 316,
    District: "Thiruchirappalli",
    Institution: "Royal Pearl Hospital",
    covid: 3,
    oxygen: 3,
    icu: 0,
  },
  {
    "S.NO": 317,
    District: "Mayiladuthurai",
    Institution: "Vishnu hospital",
    covid: 3,
    oxygen: 0,
    icu: 3,
  },
  {
    "S.NO": 318,
    District: "Sivagangai",
    Institution: "Apollo",
    covid: 5,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 319,
    District: "Sivagangai",
    Institution: "Senthil hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 320,
    District: "Chengalpet",
    Institution: "KMS Health Centre",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 321,
    District: "Salem",
    Institution: "Kamala Hospital,Agraharam",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 322,
    District: "Coimbatore",
    Institution: "Coimbatore Diabetic Foundation,maruthamalai road",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 323,
    District: "Kanyakumari",
    Institution: "Manuel Orthopedic Hospital, therekaalputhoor",
    covid: 5,
    oxygen: 0,
    icu: 5,
  },
  {
    "S.NO": 324,
    District: "Kanyakumari",
    Institution: "Joseph Sahayam Speciality Hospital, Nagerkoil",
    covid: 44,
    oxygen: 30,
    icu: 6,
  },
  {
    "S.NO": 325,
    District: "Kanyakumari",
    Institution: "Thasiah Medical centre, Marthandam",
    covid: 16,
    oxygen: 5,
    icu: 10,
  },
  {
    "S.NO": 326,
    District: "Thanjavur",
    Institution: "MVK Hospital, Thanjavur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 327,
    District: "Thanjavur",
    Institution: "Vinodhagan Memorial Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 328,
    District: "Coimbatore",
    Institution: "Chennai Hospitals Pvt Ltd, Gandhipuram",
    covid: 37,
    oxygen: 37,
    icu: 7,
  },
  {
    "S.NO": 329,
    District: "Coimbatore",
    Institution: "CSR Nursing Home, Gandhipuram",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 330,
    District: "Coimbatore",
    Institution: "Dr.Muthus Hospital, Saravanampatti",
    covid: 11,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 331,
    District: "Coimbatore",
    Institution: "FIMS Hospital, Sundarapuram",
    covid: 1,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 332,
    District: "Coimbatore",
    Institution: "K.Govindhasamy Memorial Annex Hospital, Saravanampatti",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 333,
    District: "Coimbatore",
    Institution: "Kalpana Medical Centre Pvt Ltd, Kavundampalayam",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 334,
    District: "Coimbatore",
    Institution: "Kumaran Medical Centre, Kurumbapalayam",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 335,
    District: "Coimbatore",
    Institution: "NG Hospital Pvt Ltd & Research Centre, Singanallur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 336,
    District: "Coimbatore",
    Institution: "Sathya Medical Centre and Hospital, Sivanandha Colony",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 337,
    District: "Salem",
    Institution: "Aishwaryam Speciality Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 338,
    District: "Salem",
    Institution: "Deepam Speciality Hospital, Vazhapady",
    covid: 15,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 339,
    District: "Salem",
    Institution: "GL Hospital, Swarnapuri",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 340,
    District: "Salem",
    Institution: "Mohanraj Children's Hospital",
    covid: 46,
    oxygen: 1,
    icu: 0,
  },
  {
    "S.NO": 341,
    District: "Salem",
    Institution: "Nathan Super Speciaty Hosptial, Salem",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 342,
    District: "Salem",
    Institution: "Sri Shellapha Hospital, Salem",
    covid: 10,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 343,
    District: "Salem",
    Institution: "Thiru Neuro And MultiSpecility Salem",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 344,
    District: "Erode",
    Institution: "Erode multispeciality Hospital, Erode",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 345,
    District: "Madurai",
    Institution: "Vetri Siddha Hospital, Thaniciyam (Siddha)",
    covid: 36,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 346,
    District: "Karur",
    Institution: "Abishek Hospital, Karur Tn.",
    covid: 2,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 347,
    District: "Namakkal",
    Institution: "Shree Akhshaya Hospital Namakkal, TN.",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 348,
    District: "Namakkal",
    Institution: "Soorya Multispechiality Hospitals, Namakkal TN.",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 349,
    District: "Karur",
    Institution: "GC Hospital, Karur Tn.",
    covid: 3,
    oxygen: 2,
    icu: 0,
  },
  {
    "S.NO": 350,
    District: "Chennai",
    Institution: "Vivekananda Hospital,mylapore",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 351,
    District: "Chengalpattu",
    Institution: "DAISY HOSPITAL,CHROMPET",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 352,
    District: "Chengalpattu",
    Institution: "AAYUSHMAAN HOLISTIC HEALTH CENTRE",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 353,
    District: "Kanyakumari",
    Institution: "Catherinebooth hospital,Nagercoil",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 354,
    District: "Tenkasi",
    Institution: "Mathura Hospital, Surandai",
    covid: 8,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 355,
    District: "Chennai",
    Institution: "K.M Speciality Hospital, K.K Nagar",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 356,
    District: "Tiruvallur",
    Institution: "SKS HOSPITAL",
    covid: 3,
    oxygen: 3,
    icu: 0,
  },
  {
    "S.NO": 357,
    District: "Thiruvarur",
    Institution: "P.K.T Nursing Home, Thiruthuraipoondi",
    covid: 15,
    oxygen: 15,
    icu: 4,
  },
  {
    "S.NO": 358,
    District: "Dindigul",
    Institution: "Vadamalayan Hospital",
    covid: 3,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 359,
    District: "Chennai",
    Institution: "MOHAN NURSING HOME, VILLIVAKKAM",
    covid: 8,
    oxygen: 4,
    icu: 0,
  },
  {
    "S.NO": 360,
    District: "Chennai",
    Institution: "Best Hospitals,Kodambakkam",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 361,
    District: "Thiruvarur",
    Institution: "Raj Hospital, Mannargudi",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 362,
    District: "Chengalpattu",
    Institution: "Kasthuri Hospital , Thambaram",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 363,
    District: "Chennai",
    Institution: "Sri Singhvi Health Centre, Purasaivakkam",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 364,
    District: "Namakkal",
    Institution: "Visaalam Hospital",
    covid: 13,
    oxygen: 3,
    icu: 1,
  },
  {
    "S.NO": 365,
    District: "Krishnagiri",
    Institution: "Gunam super speciality hospital,Hosur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 366,
    District: "Salem",
    Institution: "Sree jeyam ortho & multispeciality Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 367,
    District: "Krishnagiri",
    Institution: "St.Louis Hospital",
    covid: 37,
    oxygen: 37,
    icu: 0,
  },
  {
    "S.NO": 368,
    District: "Vellore",
    Institution: "Naruvi Hospitals(A Unit of m/s.Sanco )",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 369,
    District: "Krishnagiri",
    Institution: "Nathan’s Speciality Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 370,
    District: "Chennai",
    Institution: "Sudha Hospital, Royapuram",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 371,
    District: "Tirunelveli",
    Institution: "Peace Health Centre",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 372,
    District: "Chennai",
    Institution: "Jolen Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 373,
    District: "Chennai",
    Institution: "Sen Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 374,
    District: "Chennai",
    Institution: "st. Isabels hospital, Maylapore",
    covid: 26,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 375,
    District: "Chennai",
    Institution: "Sri Balaji Hospital, guindy",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 376,
    District: "Chennai",
    Institution: "Radha Rajendran Hospital, Alandur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 377,
    District: "Chennai",
    Institution: "One health hospital, Vandalur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 378,
    District: "Chennai",
    Institution: "Srinivasa Hospital, Kodampakkam",
    covid: 5,
    oxygen: 3,
    icu: 0,
  },
  {
    "S.NO": 379,
    District: "Kanyakumari",
    Institution: "PPK hospital, Marthandam",
    covid: 7,
    oxygen: 7,
    icu: 0,
  },
  {
    "S.NO": 380,
    District: "Salem",
    Institution: "RK hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 381,
    District: "Karur",
    Institution: "Nachimuthu hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 382,
    District: "Virudhunagar",
    Institution: "Amar hospital",
    covid: 2,
    oxygen: 0,
    icu: 2,
  },
  {
    "S.NO": 383,
    District: "Krishnagiri",
    Institution: "Uma Kumar Hospital, Hosur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 384,
    District: "Tirunelveli",
    Institution: "VJ Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 385,
    District: "Thiruchirappalli",
    Institution: "Atlas Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 386,
    District: "Tiruppur",
    Institution: "Velan Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 387,
    District: "Dindigul",
    Institution: "Sakthi Vinayagar Multispeciality Hospital, Guziliamparai",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 388,
    District: "Chennai",
    Institution: "Be well hospital T.Nagar",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 389,
    District: "Chennai",
    Institution: "Vijai's Nursing home",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 390,
    District: "Chennai",
    Institution: "Prime Indian Hospitals",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 391,
    District: "Thanjavur",
    Institution: "Dravidian Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 392,
    District: "Coimbatore",
    Institution: "Gem Hospital and Research centre",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 393,
    District: "Coimbatore",
    Institution: "N.M. Hospital, Annur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 394,
    District: "Namakkal",
    Institution:
      "Swamy Vivekanandha Medical College Hospital and Research Institute",
    covid: 100,
    oxygen: 40,
    icu: 10,
  },
  {
    "S.NO": 395,
    District: "Tiruvallur",
    Institution: "Be well , Ponamallee",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 396,
    District: "Thanjavur",
    Institution: "National pharma",
    covid: 15,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 397,
    District: "Thiruchirappalli",
    Institution: "Akshaya Hospital,Thottiyam",
    covid: 8,
    oxygen: 5,
    icu: 3,
  },
  {
    "S.NO": 398,
    District: "Chennai",
    Institution: "Amrit Medical Centre,Purasawakkam",
    covid: 3,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 399,
    District: "Salem",
    Institution: "AP Medical Centre",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 400,
    District: "Chennai",
    Institution: "Fortis healthcare – Vadapalani",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 401,
    District: "Chennai",
    Institution: "City Tower Hospital,Anna Nagar",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 402,
    District: "Tiruppur",
    Institution: "CNS Hospitals, Palangarai",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 403,
    District: "Chengalpattu",
    Institution: "Das Nursing Home,Chengalpattu",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 404,
    District: "Kanyakumari",
    Institution: "Dr. Kumaraswami Health Centre, Perumalpuram",
    covid: 22,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 405,
    District: "Chennai",
    Institution: "Esha Hospital,Old Washermenpet",
    covid: 3,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 406,
    District: "Chennai",
    Institution: "Faith Multispecialty Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 407,
    District: "Chennai",
    Institution: "G.R Hospital,Adambakkam",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 408,
    District: "Madurai",
    Institution: "Genezen Indus Hopsital,Madurai",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 409,
    District: "Chennai",
    Institution: "GeriCare, T Nagar",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 410,
    District: "Chennai",
    Institution: "Hindu Mission Health Services,Nanganallur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 411,
    District: "Chennai",
    Institution:
      "Iyyappa Hospitals and Diabetes Research Centre Pvt Ltd,Perambur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 412,
    District: "Kancheepuram",
    Institution: "Jaya Hospital,Sriperumbudhur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 413,
    District: "Thoothukudi",
    Institution: "Jayashri Hospital,Tuticorin",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 414,
    District: "Sivagangai",
    Institution: "Jedaiah Steve Hospital,Karaikudi",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 415,
    District: "Chennai",
    Institution: "Jyoti Hospital,Old Washermenpet",
    covid: 9,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 416,
    District: "Thanjavur",
    Institution: "Kanakesa Thevar Memorial Hospital,Thanjavur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 417,
    District: "Chengalpattu",
    Institution: "Kathir Memorial Hospital,Chengalpattu",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 418,
    District: "Salem",
    Institution: "Kavin Hospital,Omalur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 419,
    District: "Chennai",
    Institution: "Kavitha Ortho and Multi Speciality Hospital,Chrompet",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 420,
    District: "Tiruppur",
    Institution: "Kongu Heart Center, Dharapuram",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 421,
    District: "Chengalpattu",
    Institution: "Lakshmi Nursing Home, Pallavaram",
    covid: 2,
    oxygen: 2,
    icu: 0,
  },
  {
    "S.NO": 422,
    District: "Chennai",
    Institution: "Leela Specialty Hospital,Tiruvottiyur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 423,
    District: "Kancheepuram",
    Institution: "Mahalakshmi Multispecialty Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 424,
    District: "Chennai",
    Institution: "Nagamani Hospital,Old Washermenpet",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 425,
    District: "Chennai",
    Institution: "Nalam Hospital Pvt Ltd",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 426,
    District: "Chennai",
    Institution: "Oxymed Hospital,Nandanam",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 427,
    District: "Chennai",
    Institution: "Pavithra Hospital Pvt Ltd,Teynampet",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 428,
    District: "Thiruchirappalli",
    Institution: "Prabhu Diabetes Specialty Centre,Trichy",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 429,
    District: "Chennai",
    Institution: "Prasanth Fertility Research Centre,Chetpet",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 430,
    District: "Pudukkottai",
    Institution: "Pudhugai Star Hospital,Pudukottai",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 431,
    District: "Chennai",
    Institution: "Ramani Hospital,Ashok Nagar",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 432,
    District: "Chennai",
    Institution: "Right Hospitals Pvt Ltd",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 433,
    District: "Chengalpattu",
    Institution: "RKP Hospital,Nanmangalam",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 434,
    District: "Krishnagiri",
    Institution: "S.B.S. Hospital, Hosur",
    covid: 3,
    oxygen: 3,
    icu: 0,
  },
  {
    "S.NO": 435,
    District: "Namakkal",
    Institution: "Sakthi Hospital,Namakkal",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 436,
    District: "Chennai",
    Institution: "Senthil Priya Hospital, Kodungaiyur",
    covid: 1,
    oxygen: 1,
    icu: 0,
  },
  {
    "S.NO": 437,
    District: "Chennai",
    Institution: "Shens Hospital, Ashok Nagar",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 438,
    District: "Thiruchirappalli",
    Institution: "Sri AuroMa Hospital,Trichy",
    covid: 3,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 439,
    District: "Chennai",
    Institution: "Sri Chakra Multispecialty Hospital,Nanganallur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 440,
    District: "Chennai",
    Institution: "Sri Hospital, Tondiarpet",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 441,
    District: "Thanjavur",
    Institution: "Sri Kumaran Gastro Private Ltd",
    covid: 1,
    oxygen: 1,
    icu: 0,
  },
  {
    "S.NO": 442,
    District: "Chennai",
    Institution: "Sri Ranga Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 443,
    District: "Chennai",
    Institution: "Susi Hospital, Thiruvottiyur",
    covid: 3,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 444,
    District: "Madurai",
    Institution: "Thavam Hospital, K.Pudhur",
    covid: 2,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 445,
    District: "Tiruppur",
    Institution: "Vel Hospital, Dharapuram",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 446,
    District: "Tiruppur",
    Institution: "Vel Hospital,Udumalpet",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 447,
    District: "Madurai",
    Institution: "Vijaya Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 448,
    District: "Madurai",
    Institution: "Vikram Multispeciality hospital, Madurai",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 449,
    District: "Chennai",
    Institution: "Westminster HealthCare,Nungambakkam",
    covid: 4,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 450,
    District: "Madurai",
    Institution: "Ashwin Fed Specialty Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 451,
    District: "Tiruppur",
    Institution: "Bala Ortho Hospital, Dharapuram",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 452,
    District: "Madurai",
    Institution: "Iswarya Fertility Services Pvt Ltd,Ellis Nagar",
    covid: 6,
    oxygen: 2,
    icu: 3,
  },
  {
    "S.NO": 453,
    District: "Chennai",
    Institution: "Hindu Mission Hospital,Tambaram",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 454,
    District: "Salem",
    Institution: "Deepam Hospital,Salem",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 455,
    District: "Tiruvallur",
    Institution: "RIMS Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 456,
    District: "Thoothukudi",
    Institution: "Arputham Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 457,
    District: "Kanyakumari",
    Institution: "Morris Mathiys hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 458,
    District: "Kanyakumari",
    Institution: "Holy Cross Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 459,
    District: "Theni",
    Institution: "Krishnammal Memorial hospital.",
    covid: 3,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 460,
    District: "Tiruppur",
    Institution: "Sri Kumaran Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 461,
    District: "Theni",
    Institution: "NRT hospital",
    covid: 22,
    oxygen: 1,
    icu: 3,
  },
  {
    "S.NO": 462,
    District: "Coimbatore",
    Institution: "Manu Hospital",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 463,
    District: "Chennai",
    Institution: "Aditya Kamaraja Hospital Pvt Ltd,Virugambakkam",
    covid: 1,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 464,
    District: "Salem",
    Institution: "Appu Venkatachalam Medical Research Centre (P) Ltd, Kattur",
    covid: 2,
    oxygen: 0,
    icu: 2,
  },
  {
    "S.NO": 465,
    District: "Thiruchirappalli",
    Institution:
      "Assured Best Care Hospital(P) Ltd (ABC Hospital) Annamalai Nagar",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 466,
    District: "Chengalpattu",
    Institution: "Christudas Orthopaedic Speciality Hospital,East Tambaram",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 467,
    District: "Thiruchirappalli",
    Institution: "City Medical Center, Thennur",
    covid: 13,
    oxygen: 5,
    icu: 1,
  },
  {
    "S.NO": 468,
    District: "Coimbatore",
    Institution: "Coimbatore Child Trust Hospital,Singanallur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 469,
    District: "Cuddalore",
    Institution: "Cuddalore Specialty Hospital,Manjakuppam",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 470,
    District: "Thiruchirappalli",
    Institution: "Decca Hospital, Thillai Nagar",
    covid: 2,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 471,
    District: "Thanjavur",
    Institution: "Dr.Vanchilingam Hospital Pvt Ltd,K.S Nagar",
    covid: 2,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 472,
    District: "Chennai",
    Institution: "Ezhil Hospital, Tondiarpet",
    covid: 3,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 473,
    District: "Coimbatore",
    Institution: "Fathima Hospital,Podanur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 474,
    District: "Thiruchirappalli",
    Institution: "Jagadha Hospital,Thillai Nagar",
    covid: 4,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 475,
    District: "Thiruchirappalli",
    Institution: "Kanapathy Memorial Hospital, Musiri",
    covid: 14,
    oxygen: 10,
    icu: 0,
  },
  {
    "S.NO": 476,
    District: "TheNilgiris",
    Institution: "Kotagiri Medical Fellowship Hospital,Kotagiri",
    covid: 8,
    oxygen: 5,
    icu: 1,
  },
  {
    "S.NO": 477,
    District: "Ariyalur",
    Institution: "KVS Hospital Pvt Ltd,Valaja Nagaram",
    covid: 6,
    oxygen: 6,
    icu: 0,
  },
  {
    "S.NO": 478,
    District: "Salem",
    Institution: "Malar Hospital,Vazhapadi",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 479,
    District: "Thiruchirappalli",
    Institution: "Max Care Hospital, Annamalai Nagar",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 480,
    District: "Chennai",
    Institution:
      "Metro Male Clinic a unit of Gunasekaran Hospitals Pvt Ltd,Porur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 481,
    District: "Chennai",
    Institution: "Mount Specialty Hospital Pvt Ltd,Adambakkam",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 482,
    District: "Chennai",
    Institution: "New Ruthran Hospital,Aynavaram",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 483,
    District: "Perambalur",
    Institution: "Sanjjeev Hospital,Venkatesapuram",
    covid: 10,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 484,
    District: "Thoothukudi",
    Institution: "Sasi Hospital, Kovilpatti",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 485,
    District: "Salem",
    Institution: "Shri Hospitals, Shankar Nagar",
    covid: 1,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 486,
    District: "Chengalpattu",
    Institution: "Shri Isari Velan Mission Hospital",
    covid: 10,
    oxygen: 0,
    icu: 1,
  },
  {
    "S.NO": 487,
    District: "Thiruchirappalli",
    Institution: "Silverline Speciality Hospital, Thillai Nagar",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 488,
    District: "Thiruchirappalli",
    Institution: "SMS Hospital,Salai Road",
    covid: 6,
    oxygen: 2,
    icu: 2,
  },
  {
    "S.NO": 489,
    District: "Ariyalur",
    Institution: "SR Hospital,Ariyalur",
    covid: 3,
    oxygen: 0,
    icu: 1,
  },
  {
    "S.NO": 490,
    District: "Thiruchirappalli",
    Institution: "Sri Kumaran Hospital Manapparai",
    covid: 5,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 491,
    District: "Karur",
    Institution: "Sri Rathina Hospital,Muthu Nagar",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 492,
    District: "Salem",
    Institution: "Sundaram Multispecialty Hospital,Salem",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 493,
    District: "Coimbatore",
    Institution: "V.G Hospital,Thudiyalur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 494,
    District: "TheNilgiris",
    Institution: "Shiva Shakthi Hospital,Udagamandalam",
    covid: 12,
    oxygen: 1,
    icu: 0,
  },
  {
    "S.NO": 495,
    District: "Chennai",
    Institution: "Be Well Hospitals, Ambattur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 496,
    District: "Virudhunagar",
    Institution: "Chennai Hospital, Rajapalayam",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 497,
    District: "Virudhunagar",
    Institution: "MSB Hospital",
    covid: 4,
    oxygen: 1,
    icu: 1,
  },
  {
    "S.NO": 498,
    District: "Chennai",
    Institution: "New Life Hospital,Rajakilpakkam",
    covid: 1,
    oxygen: 1,
    icu: 0,
  },
  {
    "S.NO": 499,
    District: "Tiruppur",
    Institution: "Sakthi Nursing Home,Tiruppur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 500,
    District: "Virudhunagar",
    Institution: "Sri Ram Hospital - Sugasthala,Aruppukottai",
    covid: 14,
    oxygen: 5,
    icu: 2,
  },
  {
    "S.NO": 501,
    District: "Chennai",
    Institution: "Kasthuri Hospital,West Tambaram",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 502,
    District: "Tiruppur",
    Institution: "OMS Hospital Tiruppur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 503,
    District: "Tiruppur",
    Institution: "Malarpriya Hospital",
    covid: 3,
    oxygen: 1,
    icu: 0,
  },
  {
    "S.NO": 504,
    District: "Erode",
    Institution: "Veena hospital, nasiyanur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 505,
    District: "Erode",
    Institution: "Abirami Kidney Care Dr.Thangavelu Hospital, Brough Road",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 506,
    District: "Thiruchirappalli",
    Institution: "Aiyshwariya Hospital, Woraiyur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 507,
    District: "Chennai",
    Institution: "Anand Hospital,Manali",
    covid: 6,
    oxygen: 2,
    icu: 0,
  },
  {
    "S.NO": 508,
    District: "Chennai",
    Institution: "Anbu Hospital, Velachery",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 509,
    District: "Chennai",
    Institution: "ARK Hospital, Velachery",
    covid: 2,
    oxygen: 1,
    icu: 0,
  },
  {
    "S.NO": 510,
    District: "Chennai",
    Institution: "Arokya Hospital, West K.K Nagar",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 511,
    District: "Tiruvannamalai",
    Institution: "Arunai Hospital,Thenmathur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 512,
    District: "Chennai",
    Institution: "AVS Cardiac Centre,Triplicane",
    covid: 2,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 513,
    District: "Chennai",
    Institution: "B.M Hospital,Nanganallur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 514,
    District: "Erode",
    Institution: "Bewell Hospitals, Gandhiji Road",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 515,
    District: "Erode",
    Institution: "C.K.Hospital, Balasubbrayalu Street",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 516,
    District: "Chennai",
    Institution: "Care and Cure Speciality Hospital,Ayanavaram",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 517,
    District: "Tiruvallur",
    Institution: "Chennai Health Foundation, Ambatur",
    covid: 2,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 518,
    District: "Chennai",
    Institution: "Chennai National Hospital,Ernavoor",
    covid: 8,
    oxygen: 8,
    icu: 0,
  },
  {
    "S.NO": 519,
    District: "Erode",
    Institution: "CSI Hospital, Brough Road",
    covid: 10,
    oxygen: 5,
    icu: 0,
  },
  {
    "S.NO": 520,
    District: "Karur",
    Institution: "Deepa Kannan Hospital, Muthu Nagar",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 521,
    District: "Chennai",
    Institution: "Dr.Shahs Clinic,T.Nagar",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 522,
    District: "Chennai",
    Institution: "DRJ Hospitals(P) Ltd,Kolathur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 523,
    District: "Erode",
    Institution: "Erode Emergency Care Hospital, Veerappampalayam",
    covid: 3,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 524,
    District: "Chennai",
    Institution: "Eswar Medical Foundation, Kolathur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 525,
    District: "Tirunelveli",
    Institution: "Gold Child & Chest Hospital,Vannarpettai",
    covid: 5,
    oxygen: 5,
    icu: 0,
  },
  {
    "S.NO": 526,
    District: "Chennai",
    Institution: "K.C.Hospital, Avadi",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 527,
    District: "Salem",
    Institution: "K.M Natraj's Nursing Home",
    covid: 2,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 528,
    District: "Cuddalore",
    Institution: "Kalyaan Speciality Hospital, Alpet",
    covid: 1,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 529,
    District: "Erode",
    Institution: "Kalyani Kidney Care Centre, Sampath Nagar Main Road",
    covid: 23,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 530,
    District: "Madurai",
    Institution: "Karunai Multispecialty Hospital, B.B Kulam",
    covid: 2,
    oxygen: 1,
    icu: 0,
  },
  {
    "S.NO": 531,
    District: "Thiruchirappalli",
    Institution: "Kathir Hospital, Woraiyur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 532,
    District: "Chennai",
    Institution: "Khm Hospial, Anna Nagar",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 533,
    District: "Kancheepuram",
    Institution: "KPP Multispeciality Hospital, Sholinganallur",
    covid: 4,
    oxygen: 1,
    icu: 0,
  },
  {
    "S.NO": 534,
    District: "Chennai",
    Institution: "KVT Health Centre",
    covid: 2,
    oxygen: 1,
    icu: 1,
  },
  {
    "S.NO": 535,
    District: "Krishnagiri",
    Institution: "Lakshmi Hospital,Hosur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 536,
    District: "Chennai",
    Institution: "M/s Dr.V.BalajiDr.V.Seshiah Diabetes care and R Institute",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 537,
    District: "Chennai",
    Institution: "M/s K.M. Hospital, Vyarsarpadi",
    covid: 3,
    oxygen: 3,
    icu: 0,
  },
  {
    "S.NO": 538,
    District: "Thanjavur",
    Institution: "Medway Hospital, Kumbakonam",
    covid: 5,
    oxygen: 0,
    icu: 1,
  },
  {
    "S.NO": 539,
    District: "Tiruvallur",
    Institution: "MMRV Hospital, Azhinjivakkam",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 540,
    District: "Chennai",
    Institution: "MMRV Hospital, Mogappair West",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 541,
    District: "Tirunelveli",
    Institution: "Muthu Hospital, Kulavanigarpuram",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 542,
    District: "Erode",
    Institution: "Nandha Medical College and Hospital, Pitchandampalayam",
    covid: 2,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 543,
    District: "Karur",
    Institution: "Nathan Hospital, Anna Arch",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 544,
    District: "Chennai",
    Institution: "NRG Speciality Hospitals, Ramapuram",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 545,
    District: "Erode",
    Institution: "Ortho Life Hospital, Anusha Hospital Complex",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 546,
    District: "Kancheepuram",
    Institution: "PCMC Hospital, Pallavaram",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 547,
    District: "Chennai",
    Institution: "Pradeep Nursing Home, Puzuthivakkam",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 548,
    District: "Erode",
    Institution: "Senthil Multi Speciality Hospital, Perundurai Road",
    covid: 8,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 549,
    District: "Chennai",
    Institution: "SenthilPriya Hospital,Teynampet",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 550,
    District: "Krishnagiri",
    Institution: "Shree Arunachala Hospital,Krishnagiri",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 551,
    District: "Chennai",
    Institution: "Sri Pooja Maternity Clinic, Kodungaiyur",
    covid: 1,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 552,
    District: "Tiruvallur",
    Institution: "Sri Sundharsanam Hospital, Avadi",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 553,
    District: "Chennai",
    Institution: "Srushti Hospital, Ramapuram",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 554,
    District: "Krishnagiri",
    Institution:
      "St.Peter’s Medical College Hospital & Research Institute, Hosur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 555,
    District: "Thiruchirappalli",
    Institution: "Sugam Hospital, Manapparai",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 556,
    District: "Chennai",
    Institution: "Sugan Hospital, Neelangarai",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 557,
    District: "Krishnagiri",
    Institution: "Surya Multispeciality Hospital, Hosur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 558,
    District: "Chennai",
    Institution: "Swaram Medicare &Research Centre Pvt Ltd, Sholinganallur",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 559,
    District: "Chennai",
    Institution: "Trustlife Medical Centre, Panaiyur",
    covid: 4,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 560,
    District: "Namakkal",
    Institution: "Varun Hospital, Rasipuram",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 561,
    District: "Chennai",
    Institution: "Vasantha Hospital, Thiruvottiyur",
    covid: 1,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 562,
    District: "Kanyakumari",
    Institution: "Vijayakumar Hospital,Swamiyarmadam",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 563,
    District: "Kanyakumari",
    Institution: "William Hospital,Nagercoil",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 564,
    District: "Chennai",
    Institution: "Singhvi Health Center, Mint Street",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 565,
    District: "Madurai",
    Institution: "Hannah Joseph Hospital Pvt Ltd, Chinthamani",
    covid: 7,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 566,
    District: "Chennai",
    Institution: "M/s Apollo Hospitals, Tondiarpet",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
  {
    "S.NO": 567,
    District: "Chennai",
    Institution: "Anjakha Hospital, Madipakkam",
    covid: 0,
    oxygen: 0,
    icu: 0,
  },
];

function aaa(jc) {
  return `
  <div class="row">
  <div class="col-2">
    <center>
      <strong>${jc.District}</strong>
    </center>
  </div>
  <div class="col-2">
    <center>
      <strong>${jc.Institution}</strong>
    </center>
  </div>

  <div class="col-3">
    <div class="col-2">

      <center>
        <div class="text-muted">
          COVID BEDS
        </div>
        <strong>
        ${jc.covid}
        </strong>
      </center>
    </div>

    <div class="col-2">
      <center>
        <div class="text-muted">
          OXYGEN BEDS
        </div>
        <strong>
        ${jc.oxygen}
        </strong>
      </center>
    </div>

    <div class="col-2">
      <center>
        <div class="text-muted">
          ICU BEDS
        </div>
        <strong>
        ${jc.icu}
        </strong>
      </center>
    </div>
  </div>
  <div class="col-2">
    <center>
      <button type="button" class="btn btn-success">Contact</button>
    </center>
  </div>

</div>


    
    `;
}

document.getElementById("output").innerHTML = `${jcontent.map(aaa).join(" ")}`;
